instadeepai/jumanji

- README.md
- docs/environments/tsp.md
Closes #19 
Add a hyperlink to the autogenerated docs in the section on the environment registry and versions.
> docs: hyperlink to registered environments in main README

- CONTRIBUTING.md
Closes #36
Clearly stated in `CONTRIBUTING.md` that Jumanji follows the Google Style Guide.
> docs: state that we use the google style guide

- jumanji/environments/combinatorial/tsp/env.py
- jumanji/environments/games/connect4/env.py
- jumanji/environments/games/connect4/env_test.py
- jumanji/environments/games/connect4/specs.py
- jumanji/environments/games/connect4/types.py
- jumanji/types.py
Closes https://github.com/instadeepai/jumanji/issues/31.
> refactor: improve consistency of extras

- .pre-commit-config.yaml
Closes #47.
Fix the CI pipeline failing at the `flake8` linting step by switching from the GitLab link of `flake8` to the GitHub link in `.pre-commit-config.yaml`.
> fix: change flake8 link from gitlab to github to resolve failing ci

- .pre-commit-config.yaml
- jumanji/environments/__init__.py
Closes #34. 
Added another condition in the `environments` folder's `__init__.py` to check if `jumanji` is being run inside a non-Colab notebook. When it is not run in a notebook (Colab or otherwise), the `matplotlib` backend is set to an empty string - `IPython` will deduce the correct choice of backend from inspecting the OS. For example, the backend is inferred to be `MacOSX` for MacOS if we run `IPython.get_ipython().run_line_magic("matplotlib", "")`.
> fix: resolve jumanji import crash in non-terminal and non-notebook setting

- jumanji/env.py
Closes #55. 
Imported `Protocol` from `typing_extensions` instead of `typing` to ensure Python 3.7 compatibility.
> fix: import protocol from typing extensions to ensure Python 3.7 compatibility

- .github/workflows/tests_linters.yml
- jumanji/env.py
- requirements/requirements-dev.txt
- requirements/requirements.txt
Added Python version 3.7 to the continuous integration pipeline in GitHub Actions. To resolve the failing tests, I had to
> ci: added python 3.7 to github actions

- .pre-commit-config.yaml
- jumanji/environments/combinatorial/binpack/env_test.py
- jumanji/environments/combinatorial/routing/env_viewer.py
- requirements/requirements-dev.txt
> fix: solve flake8 error causing ci to fail

- jumanji/__init__.py
- jumanji/environments/combinatorial/binpack/conftest.py
- jumanji/environments/combinatorial/binpack/env.py
- jumanji/environments/combinatorial/binpack/env_test.py
- jumanji/environments/combinatorial/binpack/instance_generator.py
- jumanji/wrappers_test.py
Resolves #60 
This moves the instantiation of the instance generator for the binpack environment to the init of the binpack env.
Previously - this was done at registration.
> refactor: binpack instantiation of instance generator

- .pre-commit-config.yaml
- jumanji/environments/__init__.py
- jumanji/environments/games/connect4/env.py
- jumanji/environments/games/connect4/env_test.py
- requirements/requirements-dev.txt
- requirements/requirements.txt
- setup.cfg
- deprecate Connect4 by throwing a warning
- fix Connect4 action mask type
- downgrade pygame to support python 3.7
> feat: deprecate Connect4

- README.md
- requirements/requirements.txt
- setup.py
- Had to install Brax from source as any version after 0.0.16 (and potentially slightly before) is broken with recent versions of Jax. We will probably remove Brax from Jumanji's dependencies in the future.
> feat: increment semantic release

- requirements/requirements.txt
The pygame compatibility issue with python 3.7 first appeared in pygame 2.1.3.dev6 (pygame/pygame@a462721e) and has been fully resolved in 2.2.0.dev2 (pygame/pygame#3723, pygame/pygame#3572, pygame/pygame@aab517c7). Therefore, the requirement tightened in #67 can be relaxed and only pygame 2.1.3.* needs to be excluded.
> fix: pygame requirements

- jumanji/environments/commons/maze_utils/maze_generation.py
- jumanji/environments/routing/cleaner/generator.py
- jumanji/environments/routing/cleaner/generator_test.py
Closes #124.
The doctring is wrong in the generate_maze function. It states:
```python 
def generate_maze(width: int, height: int, key: chex.PRNGKey) -> chex.Array:
...
Args:
width: the number of rows of the maze to create.
height: the number of columns of the maze to create.
```
while it should be:
```python 
def generate_maze(width: int, height: int, key: chex.PRNGKey) -> chex.Array:
...
Args:
width: the number of columns of the maze to create.
height: the number of rows of the maze to create.
```
The generator for the cleaner environment is coherent with the wrong docstring, and thus width and height are inversed.
> fix(generator_maze): correct definition of width and height

- jumanji/wrappers.py
- jumanji/wrappers_test.py
Fixed the bad autoreset behavior described in issue #106 
Now, wrapped environment returns step_type = 2 when resetting.
Adapted corresponding test function, with assert step_type == 2.
> fix: make autoreset wrapper return 2 on reset

- jumanji/training/evaluator.py
- jumanji/training/networks/connector/actor_critic.py
The `Connector` networks are confusing `num_agents` with `num_actions`. This is not a problem in the registered version since both are 5. However, it becomes a problem when one trains on a different number of agents.
I also fixed a `squeeze` in the evaluator file.
> fix(training): connector num_agents in networks

- jumanji/environments/routing/cvrp/conftest.py
- jumanji/environments/routing/cvrp/env.py
- jumanji/environments/routing/cvrp/generator.py
- jumanji/environments/routing/cvrp/generator_test.py
Implement a `Generator` class for the CVRP environment which is responsible for generating the CVRP instances. This will include the following additions:
- A `generator.py` script added to the `cvrp` folder which implements an abstract class `Generator` and a `RandomGenerator` to create a random uniform CVRP instance. 
- A `generator_test.py` script to test the generator. 
- Modifications to `env.py` to include the generator in the `init` method and changes to `conftest.py` to include a `DummyGenerator` for testing purposes.
> feat(cvrp): generator

- requirements/requirements.txt
Closes #149. 
- Added the constraint `jax<=0.4.1` to `requirements.txt`
- Added the constraint `jaxlib<=0.4.1` (the version associated with JAX version 0.4.1) in `requirements.txt`
> fix: put upper bounds on versions of jax and jaxlib

- MANIFEST.in
- setup.py
The issue is: .npy files don't get copied during pip setup. A simple fix is to add the line 
`recursive-include * *.npy` in `MANIFEST.in`
The bug reported:
`FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/jumanji/environments/logic/sudoku/data/1000_very_easy_puzzles.npy'
Traceback (most recent call last):
File "zathura/train.py", line 25, in <module>
from jumanji.training import utils
File "/usr/local/lib/python3.8/dist-packages/jumanji/__init__.py", line 67, in <module>
database = np.load(os.path.join(sudoku_path, database_file))
File "/usr/local/lib/python3.8/dist-packages/numpy/lib/npyio.py", line 405, in load
fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: …
> fix: data copy setup

- jumanji/training/evaluator.py
- jumanji/training/loggers.py
- jumanji/training/setup_train.py
- jumanji/training/train.py
- adapt training code to run on multiple workers (e.g. TPU v4-16 and more)
> feat(training): multi-worker training

- jumanji/environments/logic/game_2048/env.py
- jumanji/environments/logic/game_2048/utils.py
- jumanji/environments/logic/game_2048/utils_test.py
This PR improves the performance of the Game2048 environment. The improvements include
- Minimizing logic inside of `jax.lax.cond` and `jax.lax.switch`
- Using `jax.vmap` over `jax.lax.scan` where possible
- A new move implementation
- A can_move implementation that validates an action without mutating the board
|      | no vmap | vmap 10<sup>3</sup> | vmap 10<sup>6</sup> |
|:-----|-:|-:|-:|
| cpu  | 64.36%  | 201.80%  | 392.29% |
| cuda | 900.12% | 1923.08% | 706.87% |
The above figure shows the total performance improvement measured as percent increase in steps/sec. For more detailed benchmarking, see [here](https://github.com/aar65537/jumanji-benchmarks).
> feat(2048): environment performance improvements

- jumanji/environments/routing/maze/env.py
Row and column were mixed up. In mazes where num_rows != num_cols, this would lead to incorrect action masks. This was fixed and the naming was changed from (x, y) to (row, col) in order to improve readability.
> fix(maze): fixed row and col in _compute_action_mask function.

- jumanji/environments/routing/robot_warehouse/conftest.py
- jumanji/environments/routing/robot_warehouse/env.py
- jumanji/environments/routing/robot_warehouse/env_test.py
- jumanji/environments/routing/robot_warehouse/utils.py
- jumanji/environments/routing/robot_warehouse/utils_test.py
- jumanji/training/loggers.py
- jumanji/training/utils.py
Fix the goal conditional for reward in robotic warehouse.
Closes #190
> fix(roboticWarehouse): goal conditional

- jumanji/wrappers.py
The `reward_spec` and `discount_spec` methods are not in `Wrapper`. As such when wrapping an environment with a reward/discount spec that is not the default (`shape=()`), the reward and discount specs are set to the default unless they are specified again in the wrapper.
For example
```python
class MyWrapper(Wrapper):
def reset(self, key):
do_some_stuff()
return self._env.reset(key)
env = Connector()
wrapped = MyWrapper(env)
env.reward_spec() == wrapped.reward_spec()  # <-- false
```
> fix: reward and discount spec not in wrapper

- jumanji/types.py
`timestep.extras` defaults to `None` and there are certain cases where this doesn't work. For example when making a wrapper and you want to add items to extras. The issue is that you don't know if the dictionary is initialized by the env or another wrapper, so you need to do something like `timestep.extras = timestep.extras or None` or `jax.lax.cond(timestep.extras is None, {}, timestep.extras)`. However both these approaches don't work in jax - first one is a concretization error and in the second the `true_fun` and `false_fun` don't have the same type structure.
If we default the extras field to `{}` then one can simply do `timestep.extras[key] = value` which solves the initialization issue.
> fix: timestep extras default value

- docs/environments/cleaner.md
- jumanji/environments/routing/cleaner/env.py
- jumanji/environments/routing/cleaner/env_test.py
Hello,
I found a bug in the cleaner environment. The dtype of the grid was incorrect and it was failing the tests. The alternative fix would be to change the spec of the grid to `int32`.
Best,
Raphael
> Fix: issue in dtype of grid in cleaner env

- jumanji/environments/routing/connector/env_test.py
- jumanji/environments/routing/cvrp/reward_test.py
- jumanji/environments/routing/mmst/utils.py
- jumanji/environments/routing/tsp/reward_test.py
- pyproject.toml
- `jax.random.KeyArray` -> `jax.random.PRNGKey`
- use `jnp.isclose` instead of `==` for assertions with `float32`
- convert MMST's `frac` variable to `int32` because numpy uses `float64` by default and Jax does not.
> ci: fix tests in pipeline

- requirements/requirements-train.txt
- requirements/requirements.txt
Sokoban introduced huggingface-hub as a requirement. It's only in requirements-train, but it's need to run jumanji, so moving it to the main requirements
> fix: requirements

- jumanji/wrappers.py
- jumanji/wrappers_test.py
There was an issue with the autoreset wrappers: they never showed you the final timestep. This is an issue if the final timestep is a truncation (discount = 1, timestep.last() = true), then we'd want this observation in order to get the next value for our value target, but currently this would not be possible.
Gym fixes does it in the same way I am proposing as can be seen [here](https://github.com/vwxyzjn/cleanrl/blob/master/cleanrl/dqn.py#L195) they place the final observation in infos. What this PR does is always place either the current observation or the terminal observation in `timestep.extras["real_next_obs"]`
Here's how I'm currently using for SAC (and it's working well there):
```
def step(
action: Array, obs: Observation, env_state: State, buffer_state: BufferState
) -> …
```
> fix: autoreset wrappers

- jumanji/training/loggers.py
- jumanji/wrappers.py
- jumanji/wrappers_test.py
- setup.cfg
- give a default behavior for `next_obs_in_extras` that is backward compatible for `AutoResetWrapper` and `VmapAutoResetWrapper`, following #223 
- handle non-numeric data in loggers (was crashing for `next_obs` of type `Observation` for instance)
- also made the `add_obs_to_extras` function take a `timestep` instead of `(state, timestep)`
> fix: default value for obs in extras

- README.md
- docs/environments/pac_man.md
- jumanji/__init__.py
- jumanji/environments/routing/pac_man/utils.py
- jumanji/training/configs/env/pac_man.yaml
In the PacMan environment, when trying to calculate all the valid actions a ghost could take (in `check_ghost_wall_collisions` in pac_man/utils.py) the `invert_mask * jnp.inf` call was producing an array full of NaN's where invert_mask == 1. This lead to all actions being valid for ghosts.
Instead, what this line should be doing is a `jnp.where` call, that conditionally replaces all 1's in `invert_mask` with `jnp.inf`.
> fix: pacman ghost valid action calculations result in NaNs

- docs/api/environments/cleaner.md
- docs/api/environments/connector.md
- jumanji/environments/routing/cleaner/env.py
- requirements/requirements-dev.txt
Removes `num_agents` from cleaner's `__init__` docs
Closes #203
> fix: remove num agents from cleaner init in docs

- jumanji/environments/packing/bin_pack/env.py
This is a copy of #224 because not all contributors signed the CLA and there was a weird commit history
Closes #243
> fix: binpack docs

- jumanji/environments/routing/pac_man/viewer.py
I have revised the variable assignment style and removed redundant code.
> As every PR requires CI testing, we discourage submitting PRs to fix one typo, one warning, etc. We recommend fixing the same issue at the file level at least (e.g., fix all typos in a file, fix all compiler warnings in a file, etc.)
I have read the above, but I wasn't sure if it applied to my case, so I submitted the PR for now. If this PR falls under the kind that should be avoided, I will close it.
> Refactor: Minor code style improvements

- jumanji/environments/routing/connector/env.py
- jumanji/environments/routing/connector/env_test.py
- jumanji/environments/routing/connector/reward.py
- jumanji/environments/routing/connector/reward_test.py
- jumanji/training/configs/config.yaml
- jumanji/training/setup_train.py
Return individual rewards from the Connector environment instead of providing the total sum of all agents' rewards. Additionally, implement all necessary changes to the test cases.
Use the `MultiToSingleWrapper` to aggregate the reward and discount during the training process.
> feat: return individual rewards in Connector env

- jumanji/types.py
See #256 
I just feel that it is a little weird that this dtype argument is both responsible for both reward and discount in "restart". But otherwise it means that there are no way to choose reward's dtype at restart time.
> Add dtype choice in step type/functions

- requirements/requirements.txt
Restrict JAX to below latest 0.4.36 release due to [this issue](https://github.com/jax-ml/jax/issues/25332)
> fix: Require jax below 0.4.36
